'use strict';

// Layout and palette ported from the confirmed September 7 job-graphs source.
// All paint stays in the owned shadow root; native SquareCoil stays untouched.
const ANALYTICS_CSS = `
:host{display:block;container:sc-analytics / inline-size;min-width:0;max-width:100%;margin:28px 0 32px;--ink:#374651;--muted:#7f92a3;--line:#dce3e8;--surface:#fff;--soft:#f4f7f9;--accent:#32a0c5;--selected:#e5f3f8;--shadow:0 2px 7px rgba(28,44,58,.035);color:var(--ink);font:12px/1.45 Arial,Helvetica,sans-serif;color-scheme:light}
:host([data-theme="dark"]){--ink:#e8edf2;--muted:#a2b3c1;--line:rgba(166,193,216,.2);--surface:rgba(20,31,41,.92);--soft:rgba(37,51,62,.84);--selected:#244858;--shadow:0 10px 28px rgba(0,0,0,.18);color-scheme:dark}
:host([data-glass="true"]){--surface:rgba(255,255,255,.8);--soft:rgba(242,247,250,.8)}
:host([data-theme="dark"][data-glass="true"]){--surface:rgba(20,31,41,.78);--soft:rgba(37,51,62,.68)}
*,*::before,*::after{box-sizing:border-box}button,input,select{font:inherit}button,a,input,select{-webkit-tap-highlight-color:transparent}button{cursor:pointer;color:var(--ink);border:1px solid var(--line);background:var(--surface);border-radius:4px;padding:7px 10px}button:hover{background:var(--selected)}button:disabled{opacity:.45;cursor:not-allowed}button[aria-pressed="true"]{color:var(--accent);background:var(--selected);border-color:transparent}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,[tabindex]:focus-visible{outline:2px solid var(--accent);outline-offset:3px}a{color:inherit;text-decoration:none}a:hover{text-decoration:underline}svg{display:block}h2,h3,p{margin:0}h2{font-size:16px;letter-spacing:-.2px}h3{font-size:14px}.muted{color:var(--muted)}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}[hidden]{display:none!important}
.panel{border:1px solid var(--line);border-radius:4px;background:var(--surface);box-shadow:var(--shadow)}.hours{padding:18px 22px 16px}.section-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.section-head p{color:var(--muted);font-size:11px;margin-top:5px}.controls{display:flex;gap:14px;align-items:center;flex-wrap:wrap}.segmented{display:inline-flex;border:1px solid var(--line);border-radius:4px;background:var(--surface);padding:3px;gap:2px}.segmented button{padding:5px 12px;border:0;background:transparent;font-size:11px;white-space:nowrap}.segmented button[aria-pressed="true"]{background:var(--selected)}.period-nav{display:flex;align-items:center;gap:4px}.period-nav button{border:0;font-size:11px;background:transparent;color:var(--muted)}.hours-main{display:grid;grid-template-columns:215px minmax(0,1fr);gap:20px;align-items:center;margin-top:18px}.hours-total{font-size:36px;line-height:1.2;letter-spacing:-1.4px;font-weight:700;font-variant-numeric:tabular-nums}.total-caption{margin-top:9px;color:var(--muted);font-size:11px}.summary-tags{display:flex;gap:8px;margin-top:13px;font-size:11px;flex-wrap:wrap}.summary-tags span{padding:3px 7px;background:var(--soft);border-radius:4px}.notice{margin-top:12px;color:var(--muted);font-size:11px}.notice:empty{display:none}.allocation{display:flex;height:7px;background:var(--soft);border-radius:5px;overflow:hidden;margin-top:14px}.allocation span{border-right:1px solid var(--surface)}.legend{display:flex;flex-wrap:wrap;gap:6px 12px;margin-top:12px}.legend button{display:flex;align-items:center;gap:6px;padding:2px 0;background:none;border:0;font-size:11px}.legend button[aria-pressed="false"]{opacity:.35}.dot{width:7px;height:7px;border-radius:50%;background:var(--job-color);flex:none}.legend strong{font-size:11px}.legend .clear{color:var(--accent);margin-left:auto}
.chart{position:relative;container:sc-chart / inline-size;min-width:0;height:150px}.chart-plot,.axis-x{position:absolute;inset:0 10px 0 34px}.chart svg{width:100%;height:100%;overflow:visible}.chart-axis{position:absolute;inset:0;pointer-events:none;color:var(--muted);font:10px/12px Arial,sans-serif}.axis-label{position:absolute;white-space:nowrap}.axis-y .axis-label{left:4px;transform:translateY(-50%)}.axis-x .axis-label{transform:translate(-50%,-100%)}.chart .grid{stroke:var(--line);stroke-width:1}.chart .hit{cursor:pointer;outline:none}.chart .hit:focus{stroke:var(--ink);stroke-width:2}.chart .dim{opacity:.13}.chart-tooltip{position:absolute;z-index:3;pointer-events:none;max-width:230px;padding:8px 10px;border-radius:4px;color:#fff;background:#35424d;box-shadow:0 4px 12px #0003;font-size:11px;transform:translate(-50%,-110%);white-space:normal}.chart-tooltip strong,.chart-tooltip span{display:block}.chart-tooltip span{font-size:10px;color:#d1dce3;margin-top:3px}.chart-empty{height:100%;display:grid;place-items:center;color:var(--muted);text-align:center;font-size:12px}.chart-large{height:285px}.graph-panel{padding:22px;margin-top:12px}.graph-panel h3{margin-bottom:14px}
.jobs-head{display:flex;align-items:center;justify-content:space-between;gap:16px;margin:28px 0 12px;flex-wrap:wrap}.jobs-heading{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.count{font-size:10px;color:var(--muted);background:var(--line);padding:2px 7px;border-radius:10px}.jobs-tools{display:flex;gap:8px;flex-wrap:wrap}.search{color:var(--ink);background:var(--surface);border:1px solid var(--line);border-radius:4px;padding:8px 10px;min-width:200px}.job-head,.job-row{display:grid;grid-template-columns:minmax(190px,1.55fr) minmax(110px,.8fr) minmax(105px,.8fr) minmax(90px,.65fr) minmax(80px,.6fr) 76px;gap:18px;align-items:center}.job-head{padding:5px 18px 7px;font-size:9px;text-transform:uppercase;letter-spacing:.6px;color:var(--muted)}.job-row{position:relative;border:1px solid var(--line);border-radius:4px;background:var(--surface);padding:19px 18px;border-left:3px solid var(--job-color);min-height:101px;margin-bottom:9px}.job-title{display:flex;gap:9px;align-items:center;flex-wrap:wrap}.job-id{font-size:10px;color:var(--job-color);background:var(--soft);border-radius:3px;padding:3px 5px;font-weight:700}.job-title strong{font-size:12px}.job-detail{display:block;font-size:10px;color:var(--muted);margin-top:7px}.status{font-size:11px;display:flex;gap:6px;align-items:center}.status .dot{background:#91a1ad}.status[data-status="RUNNING"] .dot{background:#5db498}.status[data-status="VERIFICATION_HOLD"] .dot,.status[data-status="AWAITING_CHOICE"] .dot{background:#cb9953}.row-time{font-size:19px;letter-spacing:-.3px;font-variant-numeric:tabular-nums}.row-time small{display:block;font-size:9px;letter-spacing:0;color:var(--muted);margin-top:3px}.row-actions{display:flex;flex-direction:column;gap:5px}.row-actions button{font-size:10px;padding:5px 7px}.spark{height:17px;display:flex;gap:3px;align-items:end;margin-top:6px}.spark i{width:7px;min-height:1px;background:var(--job-color);opacity:.6}.empty{padding:32px;text-align:center;color:var(--muted)}.footer{display:flex;align-items:center;justify-content:space-between;gap:15px;font-size:10px;color:var(--muted);margin-top:18px}.footer button{font-size:10px;background:transparent;border:0;color:var(--muted)}.message{padding:9px 12px;margin-bottom:12px;border:1px solid var(--line);border-radius:4px;background:var(--soft);font-size:12px}.message:empty{display:none}.table-scroll{overflow:auto}table{border-collapse:collapse;width:100%;font-size:11px}th,td{text-align:left;padding:8px;border-bottom:1px solid var(--line);white-space:nowrap}caption{text-align:left;padding:10px 0;color:var(--muted)}details{margin-top:15px}summary{cursor:pointer;color:var(--muted);font-size:11px}.mobile-label{display:none}
.job-row>div{min-width:0;overflow-wrap:anywhere}.legend button{min-width:0;max-width:100%;text-align:left}.legend button span{min-width:0;overflow-wrap:anywhere}
@container sc-chart (max-width:560px){.chart-axis[data-dense="true"] .axis-x .axis-label:nth-child(2n){display:none}}
@container sc-analytics (min-width:1450px){.hours-main{grid-template-columns:300px minmax(0,1fr)}}
@container sc-analytics (max-width:1000px){.hours-main{grid-template-columns:155px minmax(0,1fr)}.hours-total{font-size:30px}.job-head,.job-row{grid-template-columns:minmax(160px,1.3fr) 100px 100px 80px 75px 70px;gap:10px}.controls{gap:6px}.section-head{flex-wrap:wrap}}
@container sc-analytics (max-width:720px){.hours{padding:16px}.hours-main{grid-template-columns:minmax(0,1fr);gap:16px}.hours-total{font-size:32px}.chart{height:185px}.chart-large{height:240px}.job-head{display:none}.job-row{grid-template-columns:repeat(2,minmax(0,1fr));padding:16px;gap:15px}.job-row>div:first-child{grid-column:1/-1}.row-actions{grid-column:1/-1;flex-direction:row}.mobile-label{display:block;color:var(--muted);font-size:9px;letter-spacing:.6px;text-transform:uppercase;margin-bottom:5px}.jobs-tools,.search{width:100%;min-width:0}.footer{align-items:flex-start}.controls{width:100%}.period-nav{margin-left:auto}.segmented button{padding:6px 9px}.graph-panel{padding:15px}}
@media(max-width:650px){:host{margin:18px 0}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}
@media(forced-colors:active){:host{--ink:CanvasText;--muted:CanvasText;--line:CanvasText;--surface:Canvas;--soft:Canvas;--accent:LinkText;--selected:Highlight}.chart svg{forced-color-adjust:none}.job-row{border-left-color:CanvasText}.dot{forced-color-adjust:none}}
@media print{.controls,.jobs-tools,.row-actions,.footer button{display:none}.panel,.job-row{break-inside:avoid;box-shadow:none;background:#fff;color:#111}.chart-tooltip{display:none}:host{--surface:#fff;--soft:#fff;--ink:#111;--muted:#555;--line:#bbb}}
`;
module.exports = { ANALYTICS_CSS };
